version: '3.4'

services: 
    ratings:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - 5000:80
        links:
            - db
    db:
        image: mongo
        volumes:
              - mongodata:/data/db
volumes:
  mongodata:


