version: '3.4'

services: 
    ratings_system:
        build: .
        volumes:
            - .:/usr/src/app
        ports: 
            - 5000:80
        links:
            - db
    db:
        image: mongo:3.0.2